### PR TITLE
Support multiple categories for product.

### PR DESCRIPTION
**Pull request by RogerAndersson**
Add category paths to product_type.

google_product_category contains a comma separated list of all categories.
Example: parent category, sub-category 1, sub-category 2

product_type contains a comma separated list of all category paths.
Example: parent category > sub-category 1, parent category > sub-category 2

### CODE REVIEW

**Comment by RogerAndersson** [comment]
#492

**Comment by conandrum** [comment]
Hi Roger, wonder if you can help.
In facebook, I am getting "A product is missing a field: google_product_category". This happens to all my products.
How can fix this? How do I add these google categories to a product?
Thanks in advance

**Comment by AHID260** [comment]
yes

**Comment by RogerAndersson** [comment]
> Hi Roger, wonder if you can help.
> In facebook, I am getting "A product is missing a field: google_product_category". This happens to all my products.
> How can fix this? How do I add these google categories to a product?
> Thanks in advance

**Comment by RogerAndersson** [comment]
In Facebook Business Manager where you configure your product catalog data source.
You can configure data feed rules to fill in fields for each product, that is not set by the Facebook-for-Opencart extension.

See help documentation at
https://www.facebook.com/business/help/1206652516201625?id=725943027795860

**Comment by erikdemarco** [comment]
How if the category itself contain a "comma"?

For example
Category 1: House, Garden & Kitchen
Category 2: Home Improvement

How we handle that? If we do:
House, Garden & Kitchen, Home Improvement
It will be considered 3 Categories

**Pull request closed without merging**
