### PR TITLE
Fix wrong folder mapping

### PR DESCRIPTION
**Pull request by konstantinosbotonakis**
In case vqmod is installed to OpenCart 3.x the __DIR__ returns wrong folder.
The error looks like this:
/httpdocs/vqmod/vqcache/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/xxxxxx.com/httpdocs/vqmod/vqcache/vq2-system_library_facebookcommonutils.php on line 8

### CODE REVIEW

**Comment by konstantinosbotonakis** [comment]
Ways to reproduce the error:

- install OpenCart 3.x
- then install latest version of Facebook-For-OpenCart extension and follow all steps as mentioned in the installation steps. 
- then install vqmod from [https://github.com/vqmod/vqmod/releases/tag/v2.6.4-opencart](https://github.com/vqmod/vqmod/releases/tag/v2.6.4-opencart)
- logout and clear vQmod cache
- When you try to login into admin you will get the following error:
"/httpdocs/vqmod/vqcache/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/xxxxxx.com/httpdocs/vqmod/vqcache/vq2-system_library_facebookcommonutils.php on line 8""

This code change in file system/library/facebookcommonutils.php changes the __DIR__ to DIR_SYSTEM which is defined in config.php by default in OpenCart.

**Comment by konstantinosbotonakis** [comment]
For commit 98d41cb:
_ In OpenCart you have the option to rename admin folder to something else.
Then you edit config.php in order all the mappings to work with the new custom admin folder.

This fix, will work with any custom naming for admin folder, as long as admin's config.php DIR_APPLICATION is updated.

Here is a reported bug regarding this issue: #469 _

**Comment by kpanosgr** [comment]
Bravo! Your solution saved my day! This worked also for Opencart 2.1.0.2

**Comment by yao-tx** [comment]
This issue has been resolved with the latest FBE plugin (v4.0.0 and above). The reason for this issue was that the previous versions was using `__DIR__` which is the script's current directory. The developer(s) for the previous version should have used `DIR_SYSTEM` from OpenCart's `config.php` file instead, which contains the absolute path.

The new version does not have such an issue and this PR will be closed.

Thank you for your contribution!

**Pull request closed without merging**
